# Generated by Django 4.2.4 on 2023-08-04 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(blank=True, max_length=256, null=True, verbose_name='용량')),
                ('per', models.IntegerField(blank=True, null=True, verbose_name='도수')),
                ('name', models.CharField(blank=True, max_length=256, null=True, verbose_name='제품명')),
                ('company', models.CharField(blank=True, max_length=256, null=True, verbose_name='제조사')),
                ('mtrl', models.CharField(blank=True, max_length=256, null=True, verbose_name='원재료')),
            ],
            options={
                'verbose_name': '전통주',
                'verbose_name_plural': '전통주들',
                'db_table': 'traditional_liq2',
            },
        ),
    ]
