# Generated by Django 4.2.4 on 2023-08-04 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DataBase', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='tal',
            table='traditional_liq',
        ),
    ]
