# Generated by Django 4.2.4 on 2023-08-05 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataBase', '0002_alter_tal_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tal',
            name='per',
        ),
        migrations.RemoveField(
            model_name='tal',
            name='size',
        ),
        migrations.AddField(
            model_name='tal',
            name='dsc',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='상세설명'),
        ),
        migrations.AddField(
            model_name='tal',
            name='img',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='이미지'),
        ),
        migrations.AddField(
            model_name='tal',
            name='std',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='용량/도수'),
        ),
    ]
