# Generated by Django 4.2.4 on 2023-08-07 06:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spUser', '0002_rename_bcuser_spuser_alter_spuser_table'),
        ('DataBase', '0003_remove_tal_per_remove_tal_size_tal_dsc_tal_img_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tal',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(verbose_name='댓글')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='작성일')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userEmail', to='spUser.spuser', verbose_name='이름')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='DataBase.tal', verbose_name='포스트')),
            ],
            options={
                'verbose_name': '댓글',
                'verbose_name_plural': '댓글들',
                'db_table': 'Comments_data',
            },
        ),
    ]
