# Generated by Django 4.2.4 on 2023-08-08 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataBase', '0004_alter_tal_id_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='carbon',
            field=models.IntegerField(blank=True, choices=[(1, '1점'), (2, '2점'), (3, '3점'), (4, '4점'), (5, '5점')], null=True, verbose_name='탄산감'),
        ),
        migrations.AddField(
            model_name='comment',
            name='color',
            field=models.IntegerField(blank=True, choices=[(1, '1점'), (2, '2점'), (3, '3점'), (4, '4점'), (5, '5점')], null=True, verbose_name='색'),
        ),
        migrations.AddField(
            model_name='comment',
            name='flavor',
            field=models.IntegerField(blank=True, choices=[(1, '1점'), (2, '2점'), (3, '3점'), (4, '4점'), (5, '5점')], null=True, verbose_name='향'),
        ),
        migrations.AddField(
            model_name='comment',
            name='sour',
            field=models.IntegerField(blank=True, choices=[(1, '1점'), (2, '2점'), (3, '3점'), (4, '4점'), (5, '5점')], null=True, verbose_name='산도'),
        ),
        migrations.AddField(
            model_name='comment',
            name='sweet',
            field=models.IntegerField(blank=True, choices=[(1, '1점'), (2, '2점'), (3, '3점'), (4, '4점'), (5, '5점')], null=True, verbose_name='당도'),
        ),
        migrations.AddField(
            model_name='comment',
            name='total',
            field=models.IntegerField(blank=True, choices=[(1, '1점'), (2, '2점'), (3, '3점'), (4, '4점'), (5, '5점')], null=True, verbose_name='종합평가'),
        ),
    ]
