# Generated by Django 4.2.4 on 2023-08-08 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataBase', '0006_alter_comment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
