# Generated by Django 4.2.4 on 2023-08-09 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataBase', '0007_alter_comment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='carbon',
            field=models.IntegerField(choices=[(1, '1점'), (2, '2점'), (3, '3점'), (4, '4점'), (5, '5점')], default=None, null=True, verbose_name='탄산감'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='color',
            field=models.IntegerField(choices=[(1, '1점'), (2, '2점'), (3, '3점'), (4, '4점'), (5, '5점')], default=None, null=True, verbose_name='색'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='flavor',
            field=models.IntegerField(choices=[(1, '1점'), (2, '2점'), (3, '3점'), (4, '4점'), (5, '5점')], default=None, null=True, verbose_name='향'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='sour',
            field=models.IntegerField(choices=[(1, '1점'), (2, '2점'), (3, '3점'), (4, '4점'), (5, '5점')], default=None, null=True, verbose_name='산도'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='sweet',
            field=models.IntegerField(choices=[(1, '1점'), (2, '2점'), (3, '3점'), (4, '4점'), (5, '5점')], default=None, null=True, verbose_name='당도'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='total',
            field=models.IntegerField(choices=[(1, '1점'), (2, '2점'), (3, '3점'), (4, '4점'), (5, '5점')], default=None, null=True, verbose_name='종합평가'),
        ),
    ]
