# Generated by Django 4.2.4 on 2023-08-12 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataBase', '0008_alter_comment_carbon_alter_comment_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tal',
            name='like',
            field=models.IntegerField(blank=True, null=True, verbose_name='전체 like Count'),
        ),
    ]
