# Generated by Django 4.2.3 on 2023-07-29 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(blank=True, max_length=256, null=True, verbose_name='규격')),
                ('perecent', models.IntegerField(blank=True, max_length=256, null=True, verbose_name='도수')),
                ('name', models.CharField(blank=True, max_length=256, null=True, verbose_name='전통주명')),
                ('company', models.CharField(blank=True, max_length=256, null=True, verbose_name='제조사')),
                ('mtrl', models.CharField(blank=True, max_length=256, null=True, verbose_name='주원료')),
            ],
            options={
                'verbose_name': '전통주',
                'verbose_name_plural': '전통주들',
                'db_table': 'traditional_liq',
            },
        ),
    ]
