# Generated by Django 4.2.3 on 2023-07-30 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_alter_book_perecent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='perecent',
        ),
        migrations.AddField(
            model_name='book',
            name='percent',
            field=models.IntegerField(blank=True, null=True, verbose_name='percent'),
        ),
        migrations.AlterField(
            model_name='book',
            name='company',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='company'),
        ),
        migrations.AlterField(
            model_name='book',
            name='mtrl',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='mtrl'),
        ),
        migrations.AlterField(
            model_name='book',
            name='name',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='book',
            name='size',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='size'),
        ),
    ]
