# Generated by Django 4.2.3 on 2023-07-30 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0003_remove_book_perecent_book_percent_alter_book_company_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='percent',
            new_name='perecent',
        ),
    ]
