# Generated by Django 4.2.3 on 2023-07-30 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0004_rename_percent_book_perecent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='perecent',
            field=models.IntegerField(blank=True, null=True, verbose_name='perecent'),
        ),
    ]
