# Generated by Django 4.2.3 on 2023-07-30 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0005_alter_book_perecent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='company',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='제조사'),
        ),
        migrations.AlterField(
            model_name='book',
            name='mtrl',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='주원료'),
        ),
        migrations.AlterField(
            model_name='book',
            name='name',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='전통주명'),
        ),
        migrations.AlterField(
            model_name='book',
            name='perecent',
            field=models.IntegerField(blank=True, null=True, verbose_name='도수'),
        ),
        migrations.AlterField(
            model_name='book',
            name='size',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='규격'),
        ),
    ]
