# Generated by Django 4.2.3 on 2023-07-30 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0008_alter_book_company_alter_book_mtrl_alter_book_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='percent',
            new_name='per',
        ),
    ]
