# Generated by Django 4.2.4 on 2023-08-02 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spUser', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bcuser',
            new_name='SpUser',
        ),
        migrations.AlterModelTable(
            name='spuser',
            table='soolpan_user',
        ),
    ]
