# Generated by Django 4.2.4 on 2023-08-10 01:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('spUser', '0002_rename_bcuser_spuser_alter_spuser_table'),
        ('DataBase', '0008_alter_comment_carbon_alter_comment_color_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like', models.IntegerField(verbose_name='좋아요')),
                ('register_date', models.DateTimeField(auto_now_add=True, verbose_name='등록일자')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spUser.spuser', verbose_name='사용자')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DataBase.tal', verbose_name='술정보')),
            ],
            options={
                'verbose_name': '관심주류',
                'verbose_name_plural': '관심주류들',
                'db_table': 'favorite_database',
            },
        ),
    ]
