# Generated by Django 4.2.4 on 2023-08-12 04:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DataBase', '0008_alter_comment_carbon_alter_comment_color_and_more'),
        ('favorite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rel_name_tal', to='DataBase.tal', verbose_name='술정보'),
        ),
    ]
