# Generated by Django 4.2.4 on 2023-08-11 03:25

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('spUser', '0002_rename_bcuser_spuser_alter_spuser_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='제목')),
                ('text', models.TextField(verbose_name='본문')),
                ('image', models.ImageField(blank=True, null=True, upload_to='posts/', verbose_name='이미지')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='작성일')),
                ('published_date', models.DateTimeField(blank=True, null=True, verbose_name='게시일')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spUser.spuser', verbose_name='작성자')),
            ],
            options={
                'verbose_name': '나의 술자랑',
                'verbose_name_plural': '나의 술자랑들',
                'db_table': 'img_blog',
            },
        ),
    ]
